<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AnimalRegistry</RootNamespace>
    <AssemblyName>AnimalRegistry</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  </Project>
